### ISSUE TITLE
Successful using of TestNG timeOut and BrowserStrategy together

### ISSUE THREAD

**Issue by dimand58** [codeborne/selenide#194]
Request of re-opening #171
Someones will be nice to have configuration variable for re-using of WebDriver instance, instead of creating new thread (when using timeOut)

**Comment by asolntsev** [comment]
Do you mean Selenide should implement a pool of WebDrivers?

**Comment by dimand58** [comment]
I don't know what kind of solution is better, but Selenide should allow to use Testng timeOut (in @Test)  without problem (issue was descripted in #171).
If you can provide your vision of solution (with basic details) - I can help with implementation.

**Comment by asolntsev** [comment]
@dimand58 There is an easy solution. Do not call `setWebDriver()` in `before()` method, but call it directly in test. This way you will guarantee that `setWebDriver()` is called in the same thread as test itself.

Another solution would be to implementing `WebDriverProvider` instead of using `setWebDriver()`.

Generally, the problem is that Selenide holds webdrivers per-thread. In current Selenide implementation, it's not possible to call `setWebDriver()` in one thread and use this webdriver in another thread. And it's not easy to implement: it would heavily depend on testing framework. That's way I prefer to say "if you use `setWebDriver()`, it's your business to manage webdriver properly" and leave Selenide code as simple as possible.

**Comment by dimand58** [comment]
@asolntsev, thanks for clarify.
We are using our implementation of WebDriverProvider already, but problem is actual. We will try to use setWebDriver() in @Test method directly.

I think this issue can be closed.

**Comment by asolntsev** [comment]
@dimand58 If you implemented `WebDriverProvider`, you **do not need** to use `setWebDriver()`. Selenide itself calls your `WebDriverProvider` every time when it needs a browser.

So, solution for your problem is even more easy: just remove all `setWebDriver()` usages from your code.

**Comment by asolntsev** [comment]
@dimand58 Is the issue resolved?
