### ISSUE TITLE
Show path to page html in addition to screenshot

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#210]

**Comment by dmak** [comment]
I relation to this issue I have a question. Some versions ago I have noticed that Selenide does not print path to PNG as well. Maybe I should configure it using some loglevel? Thanks!

**Comment by asolntsev** [comment]
No, path to screenshot (png) should be always visible. It's not visible
only if browser failed to take screenshot (due to browser error). Please
send your error report, so that I could take a look on it.

**Comment by dmak** [comment]
That's the funny thing: I see that PNG file and HTML file are created (that means the browser succeeded to provide their contents), but I see nothing in output of Unit test (which is run in Maven). It could be that message was suppressed due to error level, but it could be that path should printed together with exception. Could you please point me to the place in Selenide code, where printing of the path should happen? Many thanks.

**Comment by dmak** [comment]
I have created a separate issue #234 for that.

**Comment by anyone-can-test** [comment]
So, how can I add the path to page html to the result?
both screenshot and html are saved, but the logs of failed tests provide only the path of screenshot in Jenkins.

**Comment by BorisOsipov** [comment]
Done in https://github.com/codeborne/selenide/pull/590
