### ISSUE TITLE
Feature request: ability to not re-spawn a browser if it crashes or is unreachable

### ISSUE THREAD

**Issue by ken-p** [codeborne/selenide#244]
Copy/paste from the google group:

It's very handy for Selenide to re-create a browser if there was a problem reaching the original one that was spawned or was set (e.g. it crashed, or the node went down, etc).

But sometimes we would prefer to let the test fail and not re-create it. Could that be added, perhaps the behavior (re-create, or not) set with a System property?

I'm guessing the change needs to be in WebDriverThreadLocalContainer.getWebDriver and .getAndCheckWebDriver().

Thanks!

**Comment by asolntsev** [comment]
@ken-p What effect you actually want to achieve?
If Selenide will not re-spawn browser, all other tests will just fail. Do you really want it?

Yes, we could add a system property (say, "") and check it in method `getAndCheckWebDriver()`. But we cannot use it in method `getWebDriver()` because this method actually need to spawn a browser.

**Comment by asolntsev** [comment]
@ken-p I added property `-Dselenide.reopenBrowserOnFail=false`, does it sound good?
