### ISSUE TITLE
Bindings to C#

### ISSUE THREAD

**Issue by neooleg** [codeborne/selenide#256]
Guys, thanks a lot for amazing tool which minimize testing time and allows release better product to users faster!

However, it's really important for your popularity to support C# with Selenide. C# community a really big as well as Java. Moreover, as for me, a good/concise API for Selenium WebDriver also will be so demanded.

**Comment by asolntsev** [comment]
@neooleg thank you for the feedback and suggestion! I believe it's a great idea to create C# port of selenide. The only problem is that we do not use C# every day, so it would not be "dog food" for us (which is key success factor for Selenide).

I would like to participate in this project with someone else.

**Comment by neooleg** [comment]
@asolntsev, I propose to discuss this in details personally. Perhaps, I can be useful.

**Comment by vinogradoff** [comment]
As far as I know, @yashaka, who started porting selenide to python (selene on github) also had plans to do c# as well 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by yashaka** [comment]
That's true... I have some working code base with main functionality... Just need to find the time to share it on github... I hope to finalize this until Selenium Camp in the end of Winter.



—

**Comment by neooleg** [comment]
@vinogradoff, @yashaka, thanks for the good news.

@yashaka, can you please share the project with me for personal use? In case, if you can't share this on GitHub now.

**Comment by yashaka** [comment]
OK, I will try to share it in the proper way on github tomorrow :-)



—

**Comment by neooleg** [comment]
@yashaka thanks a lot, looking forward to work with it :)

**Comment by vinogradoff** [comment]
Thank you guys, let us know about the progress)

**Comment by neooleg** [comment]
Guys, looks like [TestStack.Seleno project](https://github.com/TestStack/TestStack.Seleno) a bit similar to Selenide (for C#). May be a bit more specialized to PageObjects, but also has concise/fluent API.

What do you think about that?

**Comment by vinogradoff** [comment]
Selenide is a bit more, than concise/fluent API. It's also testing framework (should* methods, useful data - message, screenshot, source code - for fails) resolving the common shortcomings of plain Selenium (timeouts, ajax, staleElement)

**Comment by neooleg** [comment]
Thanks for comment. Yep, I know. However, Seleno [also has timeouts](http://seleno.teststack.net/docs/locators). Although, I agree with you, they are a bit weak than Selenide has.

I am hinting, that it would be great to share experience :wink: Anyway, let's wait until @yashaka shared own project. Hopefully, then we'll understand how to get the aim - Selenium framework for C# for creating tests simpler and faster. Like Selenide gives for Java, I suppose.

**Comment by yashaka** [comment]
So, Here it is... A very draft version, though already published to nuget gallery https://www.nuget.org/packages/NSelene/0.0.0.1.

Sources: https://www.nuget.org/packages/NSelene/0.0.0.1

The version is not tested:)
The project has no tests, no docs yet:)

But has an example tests project: https://github.com/yashaka/NSelene/blob/master/NSeleneExamples

Below you can find a short overview:

NSelene has no automatic driver management, you have to set it up manually, e.g. like here: 
```csharp
		[SetUp]
		public void SetupTest()
		{
			SetDriver (new FirefoxDriver ());
		}

		[TearDown]
		public void TeardownTest()
		{
			GetDriver ().Quit ();
		}
```
(https://github.com/yashaka/NSelene/blob/master/NSeleneExamples/BaseTest.cs)

Tests may look like this, via PageObject implemented in a "Procedural way":

```csharp
        [TestFixture ()]
        public class Test : BaseTest
        {
            [Test ()]
            public void FilterTasks ()
            {
                Tasks.Visit ();

                Tasks.Add ("a", "b", "c");
                Tasks.ShouldBe ("a", "b", "c");

                Tasks.Toggle ("b"); 

                Tasks.FilterActive ();
                Tasks.ShouldBe ("a", "c");

                Tasks.FilterCompleted ();
                Tasks.ShouldBe ("b");
            }
        }
```
(https://github.com/yashaka/NSelene/blob/master/NSeleneExamples/TodoMVC/Tests.cs)

where procedural "PageObject" may look like this:

```csharp
        public static class Tasks
        {
            public static SCollection List = SS ("#todo-list>li"); 

            public static void Visit()
            {
                Open ("https://todomvc4tasj.herokuapp.com/");
            }

            public static void FilterActive ()
            {
                S (By.LinkText ("Active")).Click ();
            }

            public static void FilterCompleted ()
            {
                S (By.LinkText ("Completed")).Click ();
            }

            public static void Add(params string[] taskTexts)
            {
                foreach (var text in taskTexts) 
                {
                    S ("#new-todo").SetValue (text).PressEnter ();
                }
            }

            public static void Toggle (string taskText)
            {
                List.FindBy (Have.ExactText (taskText)).Find (".toggle").Click ();
            }

            public static void ShouldBe(params string[] names)
            {
                List.FilterBy (Be.Visible).Should (Have.Texts (names));
            }
        }
```
So... 
The ported things are: 
- Selenide.$
- SelenideElement#should
- SelenideElement#find
- Selenide.$$
- EllementsCollection#should
- EllementsCollection#findBy
- EllementsCollection#filterBy
- Conditions.visible, Condition.exactText
- CollectionConditions.texts

The first thing I plan to do - is to implement SElement (aka SelenideElement) as something more smart than C# delegate. Because current implementation lacks abilities to support e.g. screenshots in error messages... 

Current implementation is also kind of "experimental one". It is implemented completely in non-OOP way :)
The main answer  to "Why?" - is speed. I implemented it in a few evenings. 
First I will proceed with this style of implementation (using a lot of "extension methods") just for fun and R&D :) And will switch to common OOP implementation via wrapping WebElement (like Selenide does) if needed :)

Since holidays are coming... And my schedule is very tough, I expect to make "more useful" version somewhere till the end of January. And something "more stable" covered with tests - till the end of February... 

Feel free to share your thoughts and file an issue on github if you need something.

**Comment by neooleg** [comment]
@yashaka, it's a great job despite the known issues :+1: 
Thanks for sharing! Its need to go deeper to figure out how it works and how it can be useful :wink:
