### ISSUE TITLE
Check if there is no java script error does not seem to work

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#284]
Check if there is no javascripterror does not seem to work. When opening the page i do see a javascript error in my console. However the test does not fail when opening the same page using Selenide
@Test
    public void test(){

        Configuration.browser = "Chrome";
        open("https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors");
        assertNoJavascriptErrors();

    }

**Comment by asolntsev** [comment]
@thasherwin Yes, currently Selenide can only catch JS errors that happen **after** page loading. It' because Selenide injects code for tracking JS errors **after** the page is loaded. Webdriver API doesn't allow to intercept page loading. Probably we will do it with help of BrowserMobProxy. Sometimes.

**Comment by thasherwin** [comment]
Okay clear. I will look into BrowserMobProxy and use this function only after a page load. Thanks for the quick reply.

**Comment by cbxp** [comment]
Note (if you come here by Google): this function was later deleted; there is no cross-browser way and probably custom code needs to be added to the app

**Comment by asolntsev** [comment]
This post describes how to get browser logs with a standard webdriver api:
https://selenide.org/2019/12/16/advent-calendar-browser-logs/

But afaik it's not supported by all browsers (at least it works in Chrome).
