### ISSUE TITLE
Moving tests from windows to Linux server 

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#318]
I have some tests, I am using 
- Maven 3.1 
- Selenide v3.5
- Selenium v2.53 
- Firefox v45.0.1

I run them on windows and all thing are going fine with successful run, I noticed that browser on windows is explicitly open and see the tests directly on browser.

Then I need to move this to run it on UBUNTU server, I just used Xvfb and try to run the tests.
My notice:
1. I can't see the graphical browser, I search for this thing and it is called a headless browser.
2. I got different problems with tests, some of them couldn't have a successful test and others can't find some elements! although it is worked on Windows.

My questions, what are the main points we have to consider while moving our test from windows client environment to Linux server?

I am reading about headless browsers, could I have to use one of them? or Selenium can handle this issue.

What are changes in code have to consider to run tests on server?
Or the same code should work fine on both environments?

**Comment by asolntsev** [comment]
@hana9090 
Hi!
You can run absolutely the same tests on Linux and Windows. You don't even need Xvfb or headless browsers on desktop linux (like Ubuntu).

### Xvfb
You only need Xvfb if you run tests on server-side linux (like some Jenkins server) without graphical environment. In this case Xvfb emulates graphical environment.

You can also use Xvfb on desktop linux. It gives exactly that effect: you don't see the browser, because it runs in "emulated display" provided by xvfb, not real display.

### Headless browsers
Headless browsers are PhantomJS, HtmlUnit and so on. 
You can also use them (people think that PhantomJS is a little bit faster than Chrome/Firefox). 
But yes, you cannot see them, because they do not render graphics.

**Comment by hana9090** [comment]
but why some tests failed?
for example: 
there are two tests to check links, and have same code to get links:

`		for (SelenideElement link : $$("a"))
			links.add(link.attr("href"));`

why one of test has a successful test and other can't find element <<element not found a[0]>>.

**Comment by asolntsev** [comment]
It probably depends on speed of test execution. Linux is faster, you know. :)

And browser versions are also different.
What browser+version do you use in Windows vs Linux?

**Comment by hana9090** [comment]
same version Firefox 45.0.1

**Comment by hana9090** [comment]
Should I need to remove this configuration?

`Configuration.fastSetValue = true;`

**Comment by asolntsev** [comment]
No, `fastSetValue` works well on Ubuntu too.

Actually Selenium has known issues with Firefox 45 on Linux.
We typically use an older version of Firefox (43). The whole world is waiting for fix. :)

**Comment by hana9090** [comment]
Hello @asolntsev 
what is the used version of Selenium with Selenide v3.5?

is it the new version (v2.53) or not?

**Comment by asolntsev** [comment]
Yes, the latest Selenide 3.5.1 uses the latest selenium-java 2.53.0

By the way, I just tried to run selenide tests on Ubuntu and Debian with Firefox 45 - and they work.

**Comment by vinogradoff** [comment]
You can see the version of the browser, selenide and selenium in your tests output logs. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by asolntsev** [comment]
Closing the issue.
