### ISSUE TITLE
Stop loading a page after timeout

### ISSUE THREAD

**Issue by vasilevichra** [codeborne/selenide#346]
Some times I need to force stop loading a web page by timeout (max loading but not longer than timeout). pageLoadStrategy doesn't help in this case.

If this functionality is interesting not only for me - lets do it!

How to implement it:
Future: http://stackoverflow.com/questions/28108022/running-asynchronous-code-in-java-with-timeout
And executeJavascript(): https://stackoverflow.com/questions/978740/javascript-how-to-detect-if-document-has-loaded-ie-7-firefox-3

with:
`window.stop();`

**Comment by asolntsev** [comment]
Hi @vasilevichra!
This problem is actual for us too. Sometimes Chromedriver hangs when executing our tests.
Yes, your proposed solution could help, but probably there is simpler solution.

As you know, Selenium webdriver communicates with real browser via HTTP requests.
Selenium just could use shorter timeouts for these requests.
Currently Selenium sets too big timeout (about 5 or 10 minutes), and this is hardcoded. We cannot configure/change it.

I suggest the following: we could make a pull request for selenium webdriver to make this timeout configurable. What do you think, does it resolve your problem?

**Comment by vasilevichra** [comment]
hi @asolntsev !!!

I agree with you. My proposal look like a workaround.
Making timeout in Selenium will solve this problem.
Will you make pull request?

**Comment by asolntsev** [comment]
@vasilevichra Yes, I will do the pull request.

**Comment by BorisOsipov** [comment]
Close old issue. Feel free to reopen and start disscussion again if it still needs to implement.
