### ISSUE TITLE
Could you add additional methods: byCss/byCssSelector, byClassName for class Selectors?

### ISSUE THREAD

**Issue by bravoaqa** [codeborne/selenide#360]
It's will be usefull for dev which store locators like:
By buttonAddTocart= By.cssSelector("button.btn-addToCart");
By buttonAddTocart= By.className("btn-addToCart");

**Comment by asolntsev** [comment]
Hi @bravoaqa!
I don't understand. Why can't you just use simpler form?

```java
String buttonAddTocart= "button.btn-addToCart";
String buttonAddTocart= ".btn-addToCart";
```

Do you use page objects?

If yes, both options are bad. 
What you actually need is a method in page object:

```java
public class CartPage {
  public void addToCart(String itemName) {
    $("#items").find(byText(itemName).click();
    $("button.btn-addToCart").click();
  }
}
```

So, you don't need to have those `By` constants.

**Comment by bravoaqa** [comment]
Actually I could use object String for some locators, but more appropriate object for locators it Selectors or By. Dev can think that String ".btn-addToCart" it is variable

Some locators are reusing between different test methods.

**Comment by yashaka** [comment]
I believe that original arguments for this feature request do not make much sense.
Because 

while 
```
By buttonAddTocart= By.cssSelector("button.btn-addToCart");
By buttonAddTocart= By.className("btn-addToCart");
```
is imho better than
```
String buttonAddTocart= "button.btn-addToCart";
String buttonAddTocart= ".btn-addToCart";
```
because when you add xpath as a string, it will be hard to define in usage - which "string" locator has xpath and which - css.

But the following is better than both mentioned above:

```
SelenideElement buttonAddTocart= $("button.btn-addToCart");
SelenideElement buttonAddTocart= $(".btn-addToCart");
```

Still, I believe that just for consistency it's better to implement this feature... 
It's just weird we have byId but do not have  byCss, byClassName, etc...

**Comment by bravoaqa** [comment]
I'm agree with you "It's just weird we have byId but do not have byCss, byClassName, etc..."

**Comment by asolntsev** [comment]
Ok, let's do it.
How is ready to make a pull request? :)
