### ISSUE TITLE
Selenide PageObject vs classic PageOBject. What's beeter and why?

### ISSUE THREAD

**Issue by BadNews87** [codeborne/selenide#375]
Hey Andrei, on the Selenide website you state that 

> There is a very popular style of Page Object that implies creating a separate field for every page element. This style has some disadvantages, but if you want, Selenide allows it:

I'd like to ask like to ask what are the disadvantages of the classic approach because I came across an opinion that the classic approach is better so I'd like to confront this with your opinion.

**Comment by asolntsev** [comment]
@BadNews87 Sure, I will describe it in a separate blog post.
Shortly: it doesn't support "dynamic" elements that appear later, or that could not appear at all.
Sometimes you need to search elements by text that is not constant (e.g. time). You cannot set if ahead in annotation.

For example, in Hangman game, a page contains all alphabet letters. 
1. Should you write 26 `@FindBy` elements - one for each letter?
2. What if you want to test localization? You want to switch to Russian alphabet which has 33 letters - and what?... 

Much simpler is to have PageObject without any field, but with public method `clickLetter(char letter)`

**Comment by tdelphi** [comment]
Additional question. What about caching? As far as I understand Selenide PageObjject will perform search for element every time the element is required. Selenium's @findby annotation is found only once (I assume). Is it something that might affect tests performance?

**Comment by asolntsev** [comment]
@tdelphi You are right, Selenide does perform search every time. It makes it possible to re-try search and other commands when element appears, disappears and so on. This is the key feature that makes Selenide a great tool.

As long as I measured, it doesn't make tests slower because searching is very fast in Selenium webdriver. Every search of element takes just a few of milliseconds. Please correct me if I am wrong.

**Comment by asolntsev** [comment]
I hope the question is answered. Closing the issue.
