### ISSUE TITLE
Universal Button Search

### ISSUE THREAD

**Issue by kenshir007** [codeborne/selenide#404]
As we know there are at least 3 ways to make a button:
```

<button class="second grey">Lorem Ipsum</button>

<input type="submit" class="grey" value="Lorem Ipsum">

<a href="" class="link-btn green">Lorem Ipsum</a>
```

Currently we can deal with `<a>` element using `$(By.linktext("Link")); `but I think it would be good idea to add new `By.buttonText("text")` feature;
New kinds of button can be identified by button tag if classic button, by submit if input and by By.linktext if link-button

This feature will make happy all Bootstrap users

**Comment by JasonTolotta** [comment]
> As we know there are at least 3 ways to make a button

There are many ways to create buttons not just 3.
What about divs, custom tags, span?

**Comment by kenshir007** [comment]
I said "at least"...

**Comment by JasonTolotta** [comment]
So it seems to be an impossibility then.

**Comment by kenshir007** [comment]
Well, most of other elements have '*btn' in classname so what is the problem? This feature will not cover all cases but helps with most used cases

**Comment by JasonTolotta** [comment]
This sounds very specific to Bootstrap, I would probably like something more agnostic.
I get the `button` tag and possibly the `type='submit'`, that's cool, but everything else sounds way too edge case.

In terms of `*btn` for the class name, what happens if that name is used in the context of something else? Maybe "btn" is an abbreviation for a component or a company name, who knows.

But then every time I use `By.buttonText('foo')`, it might be give me something I didn't expect.

**Comment by asolntsev** [comment]
@kenshir007 @JasonTolotta I agree that this is too bootstrap-specific.
Probably it's a good idea to create a dedicated library (or collection of components? Samples? Site?) "selenide-bootstrap". Probably we could even create many libraries like this: "selenide-angular", "selenide-jquery-mobile" etc.

But more generally, I believe that a way better idea is using IDs/classes with **business meaning**. 
When possible, I would use 
```java
$("#downloadTransactionsReport").click();
```

 instead of `$("button").click()`. In this case I don't care if it's button, span or link. 

Searching by text is also a good idea. Assuming that your button has some meaningful text like "download report" (not just "Link"), this test is also good: 

```java
$(By.linktext("Download report")).click();
```
