### ISSUE TITLE
Tests performance are dramatically dropped since Selenide version 3.10

### ISSUE THREAD

**Issue by slipwalker** [codeborne/selenide#457]
I've been using Selenide version 3.9.3 in my project for a while. Recently I decided to bump Selenide to the last new version (currently it is 4.2). But after some tests run I noticed in Allure report that tests performance are dramatically dropped in that Selenide version. After some investigation (roll back to some low versions, checking tests performance there), I found out that starting from Selenide version 3.9.10 tests performance are really dropped. All these experiments were conducted on the same tests environments, the same version of app, the same tests were run (smoke scope of tests with paralleling) and only Selenide version was different (you can see difference in two attaches I provided below). 
It looks like some changes were made in Selenide version 3.9.10 which lead to tests performance dropping (probably during fixing the issue #401 where were added synchronized on execute method of every command). Could you please take a look at this one? Would it be the reason of that performance dropped?

Attach 1 - Selenide version 3.9.3 - good tests performance

<img width="579" alt="selenide_3 9 3" src="https://cloud.githubusercontent.com/assets/720677/22147699/87940de8-df12-11e6-9d65-24f90a5326b3.png">

Attach 2 - Selenide version 3.9.10 or higher - poor tests performance

<img width="588" alt="selenide_3 9 10_or_higher" src="https://cloud.githubusercontent.com/assets/720677/22147704/8cc1e9ca-df12-11e6-82b5-3d3b7b71331c.png">

**Comment by rmarinsky** [comment]
try to use:
Configuration.pollingInterval = 25;
Configuration.collectionsPollingInterval = 25;

Maybe it help. I have no similar problems after update selenide

**Comment by slipwalker** [comment]
Thanks for the fast reply. Sadly, but it didn't help. Did you check performance of your tests on 3.9.3 Selenide version and then 3.9.10 (or higher)? Was it good enough and in the same degree as before? BTW, how many parallel threads have you had?

**Comment by vinogradoff** [comment]
@slipwalker Any chance you had one suite you could share with us? Or just a part of it, with runtime at 5+ seconds in the "fast" version.

**Comment by slipwalker** [comment]
@vinogradoff Nothing special with the tests suite. Moreover low performance is not related to the specific test, but to whole scope of the tests. Actually, switch back to Selenide 3.9.3 solved the issue, but could not be the solution for future perspective. Meanwhile, I can share with you some general structure of my suite:

```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="Smoke Suite" verbose="2"  parallel="tests" thread-count="18">
    <test name="Create Profile Card Tests">
        <classes>
            <class name="com.somepackage.sometestspackage.CreateProfileCardTests"/>
        </classes>
    </test>
    <test name="Trends Style Switching Tests">
        <classes>
            <class name="com.somepackage.sometestspackage.TrendsStyleSwitchTests"/>
        </classes>
    </test>
    <test name="User Permission Tests">
        <classes>
            <class name="com.somepackage.sometestspackage.UserPermissionTests"/>
        </classes>
    </test>
</suite>
```

**Comment by asolntsev** [comment]
@slipwalker I didn't see any performance drawback in my current work project. 
1. Can you share some working example that I could run to reproduce the problem?
2. Can the problem be caused by new version of Selenium webdriver or browser (by the way, what browser do you use)? 
3. Could you try to run your tests with Selenide 3.9.3, but latest Selenium webdriver? Or otherwise, with latest Selenide 4.2.1, but older selenium?

**Comment by admizh** [comment]
Hi @slipwalker sure, performance will be downgraded, after adding synchronization to Commands.exeute(....) - but if you start tests in parallel mode (https://github.com/codeborne/selenide/issues/401).

**Comment by asolntsev** [comment]
@admizh I don't think that this `synchronized` could cause any performance degradation even in multi-threaded tests. `synchronized` is very well optimized in Java. But every call of any webdriver method goes through http request, which is by definition much longer than 100500 of local method calls, even `synchronized`.

**Comment by slipwalker** [comment]
@admizh, yeah, I suspect that too. And frankly speaking my tests are run against Chrome browser (latest version) exactly in 20 parallel threads. 

@asolntsev Sorry, but by some reason cannot share for you my project code. What I made is changing Selenide version to new one, then to older and compare tests performance. Nothing else changed. Other dependencies, libraries, build infrastructure are the same for both cases. And what I've been encountered with, that starting from version 3.9.10 something new has been introduced that lead to tests performance dropping (at least for me). BTW, what do you mean by "Selenide 3.9.3, but latest Selenium webdriver" ? As far as I know Selenide particular version already includes specific webdriver version. Am I right? I can try this trick if you explain it to me.

**Comment by asolntsev** [comment]
@slipwalker Yes, you are right: every Selenide version includes (more exactly, **depends on**) particular webdriver version. But you can override it.

For example, 
* `selenide 3.10` depends on `selenium-java 2.53.1`, and 
* `selenide 4.3` depends on `selenium-java 3.1.0`

So, please try to declare these dependencies in your pom.xml (or build.xml):
* `selenide 4.3` and `selenium-java 2.53.1`.

Is it faster than just `selenide 4.3`?

**Comment by admizh** [comment]
@asolntsev @slipwalker  hi team,
I've done simple performance measurements through 2 scenarios:
1. Fist test performed with `Commands.public synchronized <T> T execute(..)`
2. Second test performed with `Commands.public <T> T execute(...)`

For testing, i use html page with slow redirection after click to button. This was done to increase response time for click command.:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Page</title>
    </head>
    <body>
        <a href="http://deelay.me/5000/http://ya.ru">
            <button id="slowclick">Click and wait loading new page</button>
        </a>
    </body>
</html>
```
It is test scenario, test started in 5 different threads, without forking in gradle (in one JVM):
``` java
public class SyncTest extends OnbBaseTest {

    @DataProvider(name = "loop", parallel = true)
    public static Iterator<Object[]> getDataWithStream() {
        return IntStream.range(1, 6).mapToObj(i -> new Object[]{UUID.randomUUID().toString()}).iterator();
    }

    @Test(dataProvider = "loop")
    public void testSyncForCommands(String guid) throws Exception {
        URL url = this.getClass().getResource("/pageWithSlowRedirect.html");
        open(url);
        $("#slowclick").click();
    }
}
```

### Tests duration results for two scenarios
1. Without `synchronized`: ~ Total execution time: 50 000.ms (average of 50 runs)
2. With `synchronized`: ~ Total execution time: 20 000.ms (average of 50 runs)

It is thread map for `synchronized` method:
![2017-02-26_19-13-31](https://cloud.githubusercontent.com/assets/6014483/23340994/4f3a1f3c-fc59-11e6-9c2b-b0e339afe593.png)
How you see all parallel threads are waiting click. In fact only one thread will be work.

It is thread map for `not synchronized` method:
![2017-02-26_19-18-05](https://cloud.githubusercontent.com/assets/6014483/23340998/632c249a-fc59-11e6-8c2f-8e04f0b815e9.png)

**Comment by asolntsev** [comment]
@admizh Wow! You are incredible!
Thank you for such a detailed information. I will investigate it.

**Comment by AlexanderPoleschuk** [comment]
Well... Here is some more investigation on this. (My first thought was that it's a Grid issue, but it's not...)
I've started a suite of 11 test cases in 12 threads(therefore it'll prove that it's not a thread dependency issue). All tests are ran in Chrome latest.
Selenide 3.8.1 with overriden Selenium 2.53.1 : 2m20sec
Selenide 4.3(w/o selenium dependency): 5m:18s:857ms
Selenide 4.3 + Selenium 2.53.1 - 5m:47s:804ms
Results vary a bit, but you may see a tremendous performance degradation between 3.8.1 and 4.3.
To prove that it's not a site issue, RAM issue, moon phase, whatever... I've start one more test:
Selenide 3.8.1: 2m:20s

Just to narrow the issue: 
Selenide 3.10: 5m:25s:396ms
Selenide 3.9.1: 2m:55s:687ms (but there are security notifications about insecure connection due to proxy).

As you may see smth odd happened with Selenide starting 3.10 version. As I've written before, I see that each test closes not only webdriver but proxy as well - it means that proxy is started for each test case...

Selenide 3.10(with Configuration.fileDownload = HTTPGET;): 5m:22s:340ms. And even with this option I see 
_INFO: Close proxy server: 1 -> null_ in logs.
It seems that this option doesn't work and Selenide starts proxy at any possible case.

**Comment by slipwalker** [comment]
@admizh well done! I confirm everything you described above. The same happened to my tests as well.

**Comment by asolntsev** [comment]
@AlexanderPoleschuk Wow. Thank you. I will research this problem.

**Comment by fyrewall77** [comment]
I am having the same issue with all my threads blocking on Commands.execute().  Perhaps ThreadLocal?

**Comment by asolntsev** [comment]
David,
Thank you!!! You are the champion!
Your really helped to solve this issue.

Of course, the problem is with *synchronized* method Commands.execute(). It
should not be synchronized.
Now I see that my commit
https://github.com/codeborne/selenide/commit/966f1b248cdf13737787bf848079a260f0383256
contained one stupid change. :(

I will fix it asap.

Andrei Solntsev

2017-03-24 8:14 GMT+02:00 David Phillips <notifications@github.com>:

**Comment by slipwalker** [comment]
Cool. As you could see this commit was exactly mentioned on the very first message of this topic ). Two months passed, many assumptions about the issue and we finally got the root of it (funny, but which was described on the beginning). Anyway, it's great that we found the reason at least such way ).

**Comment by asolntsev** [comment]
Yes, it's right: this commit was mentioned at the very beginning.
But that time I reviewed it and didn't find any problems. My bad :(

Andrei Solntsev

2017-03-25 13:29 GMT+02:00 slipwalker <notifications@github.com>:

**Comment by asolntsev** [comment]
@slipwalker @admizh @rmarinsky @vinogradoff @AlexanderPoleschuk @fyrewall77

Hi!
We have resolved this issue and released Selenide 4.4. Can you check if it helped?

**Comment by AlexanderPoleschuk** [comment]
Works like a charm! Execution time is back to normal with Selenide 4.4. Thanks for the fix!

**Comment by slipwalker** [comment]
@asolntsev really appreciate! It works now as intended.

**Comment by fyrewall77** [comment]
Works well...

**Comment by asolntsev** [comment]
@slipwalker @admizh @rmarinsky @vinogradoff @AlexanderPoleschuk @fyrewall77

FYI: I didn't get this error because I run tests with Gradle. Gradle run parallel tests in different **processes**, not threads. As a result, tests do not experience any problem with static fields, synchronized blocks etc. Don't you want to migrate to Gradle? I believe it's better than Maven in many aspects.

**Comment by fyrewall77** [comment]
I'm not running Selenide as tests, but as a webpage scraper.

**Comment by slipwalker** [comment]
@asolntsev good idea, but not in my current project. Anyway, it is worth getting more deeply into Gradle.
