### ISSUE TITLE
Clicking elements with opacity 0 raises element should be visible exception.

### ISSUE THREAD

**Issue by JKazma** [codeborne/selenide#543]
When I initialize a selenium WebElement using getWebDriver().findElement(...) and that element has opacity 0, I can still click it without any issues. However, when I initialize a SelenideElement using $(...) also with opacity 0, then a click action raises an element should be visible exception.

The reason opacity is set to zero is to cover up inputs such as checkboxes or dropdown menus with different icons/images for styling purposes which is a very common practice.

**Comment by iCok** [comment]
Could you pls provide html code of page and java code that repoduces error.

**Comment by JKazma** [comment]
@iCok Sorry for the delay.

Here's a sample code.

https://gist.github.com/JKazma/9fc9020808fc5b0de14261ec19791d54

**Comment by rosolko** [comment]
It's not possible due to selenide check that element is displayed before click and then perform a click.
Using raw selenium example you just click on item without any verification.
If you execute `getWebDriver().findElement(By.id("2")).isDisplayed()` it return `false` and click can't be performed as child of this verification.
