### ISSUE TITLE
Selenide mixes names of screenshots in case of parallel run

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#570]
... using `@Rule Screenshooter` (JUnit) or `@Listeners{Screenshooter.class}` (TestNG).

### Problem description
Selenide stores name of current test in field `ScreenShotLaboratory#currentContext`, but the instance of ScreenShotLabaratory is hold in a singleton: 

```
public class Screenshots {
  public static ScreenShotLaboratory screenshots = new ScreenShotLaboratory();
```

Effectively, it's broken when tests are executed in parallel threads.

**Comment by jane-ryabchenko** [comment]
Looks like I can solve this problem by changing ScreenShotLaboratory.currentContext and ScreenShotLaboratory.currentContextScreenshots to a ThreadLocal<String> and ThreadLocal<List<File>> correspondingly. Wdyt?

**Comment by asolntsev** [comment]
Fixed in Selenide 4.7 with PR #595 
@jane-ryabchenko thank you!

**Comment by tngii** [comment]
@asolntsev as far as i see fix from this issue was reverted  (https://github.com/selenide/selenide/commit/c21377eeccc759ddfe7b480749ccd6c14d4c423a#diff-32b811375bcf1da3a7e584b092bb947d).. now if tests run in parallel (via TestNG) - configs can be used non-static (SelenideConfig instead of Configuration) but reportsFolder for screenshot is taken from static ScreenShotLaboratory instance and all screenshots are put in one folder (default folder). Is there any solution to solve this issue ?

**Comment by asolntsev** [comment]
@tngii No, I don't think so.
I have reviewed commit [c21377e](https://github.com/selenide/selenide/commit/c21377eeccc759ddfe7b480749ccd6c14d4c423a#diff-32b811375bcf1da3a7e584b092bb947d) and see that nothing got reverted. During parallel run, a non-static `config.reportsFolder()` is used which can be different for different threads. 

If you can reproduce the problem, please share the details. A code snippet would be ideal.
