### ISSUE TITLE
shouldNotHave(text(EMPTY_STRING)) operator isn't working

### ISSUE THREAD

**Issue by AlexMMelnikov** [codeborne/selenide#574]
My code:
private static final String EMPTY_STRING = "";
SelenideElement Element = $(byClassName("phone-box"))
Element.shouldNotHave(text(EMPTY_STRING));

=> Test failed with message:
Element should not have text '' {By.className: phone-box}
Element: '<span class="phone-box">+7 499 955-56-58</span>'

!!!!BUT!!!!
Operator Assert.assertFalse(Element.text().equals(EMPTY_STRING)); is working fine.

**Comment by BorisOsipov** [comment]
Hi @AlexMMelnikov 
could you provide simple html page to reproduce problem?

**Comment by AlexMMelnikov** [comment]
Hello. Yes, sure - https://aurora-tech.ru/

**Comment by SergeyPirogov** [comment]
sholdNotBe(empty) work well

**Comment by BorisOsipov** [comment]
@AlexMMelnikov 
I guess it isn't Selenide issue.
Explanation:
- text(EMPTY_STRING) uses String.contains() and "" occurs between every character and also at start and end of string. That's why shouldNOT assert fails.
- text().equals(EMPTY_STRING) - uses String.equals() and "" is not equal any non-empty string.

Hope I helped you.

**Comment by asolntsev** [comment]
@AlexMMelnikov Exactly. Methods `$.shouldHave(text(...))` and `$.shouldNotHave(text(...))` mean **substring**. Both methods are nonsence with empty string parameter. 

(Probably they could throw an exception (or at least write warning) when empty parameter is given.)

What you actually need is `$.sholdNotBe(empty)`
