### ISSUE TITLE
Feature request: isDisplayed polling

### ISSUE THREAD

**Issue by ken-p** [codeborne/selenide#683]
I've found on a few occasions that it would be handy to have isDisplayed wait for X amount of milliseconds (while polling at Y interval), and then return true if the element is found to be displayed, or false if the timer expires. I could easily enough write my own method to do that (or a custom command), but having it built into Selenide would be great. Something like:

`boolean didIFindIt = $(".some_locator").isDisplayed(10000);`

As you know, the current isDisplayed returns right away, and the waitUntil / shouldBe methods will throw an exception if the element isn't found. I'd just like a true/false to be returned with some polling over an interval.

What do you think?

**Comment by vinogradoff** [comment]
We do not encouraged to use conditionals for ui elements visibility in your
tests. The tests should have none.

Viele Grüße

Alexei Vinogradov

On 24. Januar 2018 at 21:53:57, Ken P (notifications@github.com) wrote:

I've found on a few occasions that it would be handy to have isDisplayed
wait for X amount of milliseconds (while polling at Y interval), and then
return true if the element is found to be displayed, or false if the timer
expires. I could easily enough write my own method to do that (or a custom
command), but having it built into Selenide would be great. Something like:

boolean didIFindIt = $(".some_locator").isDisplayed(10000);

As you know, the current isDisplayed returns right away, and the waitUntil
/ shouldBe methods will throw an exception if the element isn't found. I'd
just like a true/false to be returned with some polling over an interval.

What do you think?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codeborne/selenide/issues/683>, or mute the thread

**Comment by asolntsev** [comment]
@ken-p I agree. Can you name a real case where such method would be useful?

**Comment by ken-p** [comment]
We have a lot of dynamic data in tables, and that the presence or absence of (for example) a row does not necessarily mean that the test should fail. I agree this is an edge case for normal UI testing and I can go the custom command route. Please close if you don't see the usefulness for this in the Selenide project.

**Comment by vinogradoff** [comment]
a tip:


you can divide your tests:

where the fields don’t matter - just don’t check at all

where they do matter - fail the test


logic in tests is a fast way to flakyness :)




Viele Grüße

Alexei Vinogradov

On 25. Januar 2018 at 01:02:23, Ken P (notifications@github.com) wrote:

We have a lot of dynamic data in tables, and that the presence or absence
of (for example) a row does not necessarily mean that the test should fail.
I agree this is an edge case for normal UI testing and I can go the custom
command route. Please close if you don't see the usefulness for this in the
Selenide project.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/codeborne/selenide/issues/683#issuecomment-360315801>,
or mute the thread
