### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by rosolko** [codeborne/selenide#700]
## Suggestion
Let's stick the releases to [semantic versioning](https://semver.org/).
It's really good practice.

**Comment by BorisOsipov** [comment]
+1 
SemVer is good.

**Comment by rosolko** [comment]
Summon @asolntsev and @vinogradoff to make decision!

**Comment by asolntsev** [comment]
Yes, why not.
But what exactly should we change compared to current process?

**Comment by rosolko** [comment]
@asolntsev Also all releases should be match pattern: `<major>.<minor>.<patch>`.
As for now releases can't have version `4.10` for example, it's should be `4.10.0`.

**Comment by vinogradoff** [comment]
https://semver.org/


we could actually do it, I see no problems….

Viele Grüße

Alexei Vinogradov

On 12. März 2018 at 11:15:12, Aliaksandr Rasolka (notifications@github.com)
wrote:

@asolntsev <https://github.com/asolntsev> Also all releases should be match
pattern: <major>.<minor>.<patch>.
As for now releases can't have version 4.10 for example, it's should be
4.10.0.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codeborne/selenide/issues/700#issuecomment-372258157>,
or mute the thread

**Comment by rosolko** [comment]
You don't.

**Comment by rosolko** [comment]
Looks good now.
